### ISSUE TITLE
Unable to use WHERE clause on fields with hyphen in name

### ISSUE THREAD

**Issue by tsproull** [jsayol/FireSQL#13]
For example, the collection we're using has a field that looks like this:
`app-version: "4.0"`

**Running this method:**

`await fireSQL.query("select * from  app_versions where app-version='4.0'").then(documents => {
        res.locals.response = {
            'result': 'success',
            'entities': documents
        };`

**Exception:**

```
Error: Unsupported WHERE type on left side.
    at Object.assert (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/utils.js:6:15)
    at Object.applyWhere (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/select/where.js:51:21)
    at SelectOperation.generateQueries_ (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/select/index.js:111:31)
    at Object.<anonymous> (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/select/index.js:51:40)
    at step (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/select/index.js:32:23)
    at Object.next (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/select/index.js:13:53)
    at /Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/select/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/select/index.js:3:12)
    at Object.select_ (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/select/index.js:45:12)
    at FireSQL.<anonymous> (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/firesql.js:114:52)
    at step (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/firesql.js:43:23)
    at Object.next (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/firesql.js:24:53)
    at /Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/firesql.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/firesql.js:14:12)
    at FireSQL.query (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/node_modules/firesql/firesql.js:106:16)
    at queryData (/Users/tsproull/Downloads/apiproxy 25/resources/hosted/app/apis/firestore/firestoreQuery.js:72:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by tsproull** [comment]
Surrounded the field with grave symbol, which solved the problem
